spring:
  datasource:
    url: ${secrets.DB_URL}
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secrets.MAIL_USERNAME}
    password: ${secrets.MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret-key: ${secrets.JWT_SECRET_KEY}
  expiration-hours: 3
  issuer: cow
