server:
  port: 8080

spring:
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/ddingmate
    username: root
    password: tlarbckd@17
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
