server:
  port: 8080

spring:
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://{path}
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
