spring:
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://ddingmate-database.cly6q246c2da.ap-northeast-2.rds.amazonaws.com:3306/ddingmate
    username: admin
    password: tlarbckd17
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: sgc11107@gmail.com
    password: isbcktrtacjjyark
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret-key: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
  expiration-hours: 3
  issuer: colabear754
