name: dding-mate server CI/CD

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

env:
  S3_BUCKET_NAME: dding-mate-deploy

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    -name: Set up JDK 17
     uses: actions/setup-java@v1
     with:
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
